
// load manually evasions to be able to compile them into the binary
import 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime'
import 'puppeteer-extra-plugin-stealth/evasions/console.debug'
import 'puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow'
import 'puppeteer-extra-plugin-stealth/evasions/media.codecs'
import 'puppeteer-extra-plugin-stealth/evasions/navigator.languages'
import 'puppeteer-extra-plugin-stealth/evasions/navigator.permissions'
import 'puppeteer-extra-plugin-stealth/evasions/navigator.plugins'
import 'puppeteer-extra-plugin-stealth/evasions/navigator.vendor'
import 'puppeteer-extra-plugin-stealth/evasions/navigator.webdriver'
import 'puppeteer-extra-plugin-stealth/evasions/user-agent-override'
import 'puppeteer-extra-plugin-stealth/evasions/webgl.vendor'
import 'puppeteer-extra-plugin-stealth/evasions/window.outerdimensions'
import 'puppeteer-extra-plugin-stealth/evasions/_template'